### 新增前端应用
POST {{base_url}}/iam/front/apps
Content-Type: application/json

{
  "terminal": "WEB",
  "rootPath": "/event",
  "name": "事件中心",
  "orderNum": 0,
  "config": "none"
}

### 导出应用配置信息
GET {{base_url}}/iam/front/apps/508081442220146688/export

### 导入应用配置
POST {{base_url}}/iam/front/apps/import
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="app_config_508081442220146688.json"
Content-Type: application/json

< ../../config/ops/import_front_apps/app_config_508081442220146688.json

### test
GET {{base_url}}/iam/oauth2/token
Authorization: {{token_type}} {{access_token}}
x-tenant-id: {{tenant_id}}
x-auth-app-id: {{app_id}}