### 新增前端应用
POST {{base_url}}/iam/front/apps
Content-Type: application/json

{
  "terminal": "WEB",
  "rootPath": "/event",
  "name": "事件中心",
  "orderNum": 0,
  "config": "none"
}

### 导出应用配置信息
GET {{base_url}}/iam/front/apps/622416657016422400/export

### 导入应用配置
POST {{base_url}}/iam/front/apps/import
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="app_config_622416657016422400.json"
Content-Type: application/json

< ../app_configs/app_config_622416657016422400.json

###
