### 创建平台
POST {{base_url}}/iam/platforms
Content-Type: application/json
Authorization: {{token_type}} {{access_token}}
x-tenant-id: {{tenant_id}}
x-auth-app-id: {{app_id}}

{
  "code": "customer",
  "name": "客户平台",
  "openName": "苏州算力平台",
  "note": "苏州算力平台",
  "registrable": true,
  "config": "{}"
}

### 更新平台信息
PUT {{base_url}}/iam/platforms/customer
Content-Type: application/json
Authorization: {{token_type}} {{access_token}}
x-tenant-id: {{tenant_id}}
x-auth-app-id: {{app_id}}

{
  "name": "客户平台",
  "openName": "苏州算力平台",
  "note": "苏州算力平台1",
  "registrable": false,
  "config": "{}"
}

### 删除平台
DELETE {{base_url}}/iam/platforms/customer
Authorization: {{token_type}} {{access_token}}
x-tenant-id: {{tenant_id}}
x-auth-app-id: {{app_id}}

### 获取所有平台列表
GET {{base_url}}/iam/platforms
Authorization: {{token_type}} {{access_token}}
x-tenant-id: {{tenant_id}}
x-auth-app-id: {{app_id}}

###
