### 获取用户在指定安全容器上所有可见的权限ID
GET {{base_url}}/iam/tbac/test/visible_permission_ids
    ?userId=622790509043122176
    &containerId=1

### 获取用户拥有指定权限的容器id列表
GET {{base_url}}/iam/tbac/test/authority_container_ids
    ?userId=622790509043122176
    &authority=cmdb.group:edit
    &baseContainerId=1

### 过滤用户在指定安全容器上有权限的权限ID列表
GET {{base_url}}/iam/tbac/test/container_permission_ids
    ?userId=622790509043122176
    &containerId=2
    &permissionIds=622430129179590656,622429912589926400

### 批量过滤用户在指定安全容器上有权限的权限ID列表
GET {{base_url}}/iam/tbac/test/container_permission_ids/batch
    ?userId=622790509043122176
    &containerIds=1,2
    &permissionIds=622430129179590656,622429912589926400

### 判断用户在指定安全容器上是否拥有指定权限
GET {{base_url}}/iam/tbac/test/has_authority
    ?userId=622790509043122176
    &containerId=2
    &authority=cmdb.resource.update

### 判断用户在指定安全容器上是否拥有任一权限
GET {{base_url}}/iam/tbac/test/has_any_authority
    ?userId=622790509043122176
    &containerId=52
    &authorities=cmdb.resource.read,cmdb.resource.update

### 判断用户在指定安全容器上是否拥有所有权限
GET {{base_url}}/iam/tbac/test/has_all_authority
    ?userId=622790509043122176
    &containerId=2
    &authorities=cmdb.resource.read,cmdb.resource.update

### 判断用户是否拥有API接口的访问权限
GET {{base_url}}/iam/tbac/test/has_api_permission
    ?userId=622790509043122176
    &containerId=1
    &method=GET
    &path=/cmdb/model

### 判断是否需要mfa验证
GET {{base_url}}/iam/tbac/test/need_mfa
    ?userId=627104330800955392
    &containerId=1
    &permissionId=512879011144138752

### 刷新用户权限缓存
POST {{base_url}}/iam/tbac/test/update_user_auth_latest_refresh_timestamp
    ?userId=622790509043122176

### 获取用户可见安全容器树
GET {{base_url}}/iam/tbac/test/visible_container_tree
    ?userId=622790509043122176
    &authority=cmdb.group:edit

### 获取用户在指定安全容器之上的所有可见父容器
GET {{base_url}}/iam/tbac/test/visible_container_parent_tree
    ?userId=622790509043122176
    &containerId=112
    &authority=cmdb.group:edit
