### 新增租户
POST {{base_url}}/iam/platforms/customer/tenants
Content-Type: application/json
Accept-Language: en-US

{
  "containerId": 1,
  "name": "上海理想",
  "abbreviation": "ideal",
  "note": "",
  "systemEdition": "base"
}

###
