spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://127.0.0.1:5432/ideal?currentSchema=iam&charset=UTF8"
    username: zzsong
    password: include203
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 0
      maximum-pool-size: 100
      idle-timeout: 300000
      connection-test-query: 'select 1'
      transaction-isolation: 2
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update

ideal-iam:
  permission:
    tbac:
      cache-enabled: true

ideal:
  namespace: iam6

logging:
  charset:
    file: utf-8
    console: utf-8
  level:
    root: info
    cn.sh.ideal.iam: debug
    cn.idealio.framework: info
    reactor.rabbitmq.Receiver: warn
    io.netty.resolver.dns.DnsServerAddressStreamProviders: off
    org.springframework.core.LocalVariableTableParameterNameDiscoverer: error
  pattern:
    console: '%d{HH:mm:ss.SSS} %clr(%5p) [%15.15t] %clr(%-40.40logger{39}){cyan} %clr(%6L){magenta} : %clr([%X{x-ideal-trace-id},%X{x-ideal-span-id}]){cyan} %m%n'

