server:
  port: 30030
  shutdown: graceful
  tomcat:
    threads:
      max: 512
spring:
  application:
    name: IAM
  #  threads:
  #    virtual:
  #      enabled: true
  messages:
    basename: 'i18n/iam'
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
      enabled: true
  main:
    allow-bean-definition-overriding: true

ideal-iam:
  security:
    permit-matchers:
      - /iam/login/**

ideal:
  trace:
    exclude-patterns:
      - /actuator/**
