server:
  port: 30030
  shutdown: graceful
  tomcat:
    threads:
      max: 512
spring:
  application:
    name: IAM
  #  threads:
  #    virtual:
  #      enabled: true
  messages:
    basename: 'i18n/iam'
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
      enabled: true
  main:
    allow-bean-definition-overriding: true

ideal-iam:
  ops:
    ip-whitelist:
      - 127.0.0.1
      - 172.17.0.1
      - 192.168.0.0/16
  security:
    permit-matchers:
      - /iam/ops/**
      - /iam/login/password
      - /iam/register/user
      - /iam/register/tenant

ideal:
  trace:
    exclude-patterns:
      - /actuator/**
