spring:
  config:
    import:
      - optional:application-sms-ihuyi.yml
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://127.0.0.1:27017/ideal
    redis:
      host: 127.0.0.1
      port: 6379

ideal-common-service:
  fss:
    default-engine: s3
    s3-engine:
      shard-list:
        - shard: '1'
          endpoint: 'http://127.0.0.1:9000'
          bucket: 'common-service'
          access-key: 'minioadmin'
          secret-key: 'minioadmin'
          weight: 500
          writeable: true
          base-presigned-url: 'http://127.0.0.1:9000'


ideal:
  sms:
    provider: ihuyi
    ihuyi:
      api-id: C81357548
      api-key: fefef20e767401244c17da8af6df4593
#      host: "http://127.0.0.1/webservice/sms.php?method=Submit"

logging:
  charset:
    file: utf-8
    console: utf-8
  level:
    root: info
    cn.idealio.cs: debug
    cn.idealio.framework: info
    reactor.rabbitmq.Receiver: warn
    io.netty.resolver.dns.DnsServerAddressStreamProviders: off
    org.springframework.core.LocalVariableTableParameterNameDiscoverer: error
  pattern:
    console: '%d{HH:mm:ss.SSS} %clr(%5p) [%15.15t] %clr(%-40.40logger{39}){cyan} %clr(%6L){magenta} : %clr([%X{x-ideal-trace-id},%X{x-ideal-span-id}]){cyan} %m%n'

